spring.application.name=sales_savvy

server.port=9090
spring.datasource.url=jdbc:mysql://localhost:3306/sales_savvy
spring.datasource.username=root
spring.datasource.password=shanvaz@2806

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

razorpay.key.id=rzp_test_TOoWRSL7X7maK7
razorpay.key.secret=gMshcu4iIXJkYN3Q9PzqFl6m
